#!/usr/bin/env python3
"""Find every explicit Sonnet subagent spec in the skills directory.

Scans `commands/**/*.md` for lines that pin a subagent to Sonnet via
`model: "claude-sonnet-..."` or `model: "sonnet"`. For each hit, it grabs
nearby context to identify the agent role (preceding markdown header, or
the line itself if the model is named on a "spawn ... (model: ...)" line).

Output: a markdown report at `drafts/sonnet-subagents.md` grouped by file,
with clickable file:line refs for each occurrence.

Usage:
    py -3 tools/find-sonnet-subagents.py
"""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
COMMANDS = REPO / "commands"
OUT = REPO / "drafts" / "sonnet-subagents.md"

# Match: model: "sonnet" or model: "claude-sonnet-4-6" (quotes optional, single or double)
MODEL_LINE = re.compile(r'model\s*:\s*["\']?(?P<model>sonnet|claude-sonnet-[\w.\-]+)["\']?')

# Find the closest preceding markdown header (####, ###, ##, #) for a hit's role
HEADER = re.compile(r'^(#{1,6})\s+(.+?)\s*$')

# Same-line "spawn ... (... model: ...)" parenthetical — often names the role inline
INLINE_ROLE = re.compile(
    r'\*\*([^*]+)\*\*\s*(?:subagent|agent)?\s*\([^)]*model\s*:', re.IGNORECASE
)


def find_role_for_line(lines: list[str], idx: int) -> str:
    """Walk backwards to find the nearest non-empty header that names this subagent."""
    # Try inline role on the hit line first (e.g. "spawn a **Coder** agent (model: ...)")
    m = INLINE_ROLE.search(lines[idx])
    if m:
        return m.group(1).strip()

    # Fall back to nearest preceding markdown header
    for j in range(idx - 1, max(-1, idx - 40), -1):
        hm = HEADER.match(lines[j])
        if hm:
            return hm.group(2).strip()
    return "(no header found)"


def scan_file(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    hits = []
    for i, line in enumerate(lines):
        m = MODEL_LINE.search(line)
        if not m:
            continue
        hits.append({
            "lineno": i + 1,
            "model": m.group("model"),
            "line": line.strip(),
            "role": find_role_for_line(lines, i),
        })
    return hits


def relpath(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def main():
    files = sorted(COMMANDS.rglob("*.md"))
    by_file: dict[Path, list[dict]] = {}
    total = 0
    role_count: dict[str, int] = {}
    model_count: dict[str, int] = {}

    for f in files:
        hits = scan_file(f)
        if hits:
            by_file[f] = hits
            total += len(hits)
            for h in hits:
                role_count[h["role"]] = role_count.get(h["role"], 0) + 1
                model_count[h["model"]] = model_count.get(h["model"], 0) + 1

    OUT.parent.mkdir(parents=True, exist_ok=True)

    out_lines: list[str] = []
    out_lines.append("# Explicit Sonnet Subagents — Audit\n")
    out_lines.append(
        f"Scanned `{relpath(COMMANDS)}/**/*.md`. Found **{total}** explicit Sonnet "
        f"subagent specs across **{len(by_file)}** files.\n"
    )
    out_lines.append("Generated by `tools/find-sonnet-subagents.py`.\n")

    out_lines.append("## Model variants seen\n")
    for model, count in sorted(model_count.items(), key=lambda kv: -kv[1]):
        out_lines.append(f"- `{model}` — {count}")
    out_lines.append("")

    out_lines.append("## Top roles (by name)\n")
    for role, count in sorted(role_count.items(), key=lambda kv: -kv[1])[:25]:
        out_lines.append(f"- {role} — {count}")
    out_lines.append("")

    out_lines.append("## Per-file breakdown\n")
    for f, hits in sorted(by_file.items()):
        rel = relpath(f)
        out_lines.append(f"### [{rel}]({rel}) — {len(hits)} hit(s)\n")
        for h in hits:
            link = f"[{rel}:{h['lineno']}]({rel}#L{h['lineno']})"
            out_lines.append(f"- {link} — **{h['role']}** — `{h['model']}`")
            out_lines.append(f"  - `{h['line']}`")
        out_lines.append("")

    OUT.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {relpath(OUT)} — {total} hits across {len(by_file)} file(s).")


if __name__ == "__main__":
    main()
