FROM mcr.microsoft.com/devcontainers/base:bookworm

# Example: install project dependencies
# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#     --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
#     apt-get update && apt-get -y install --no-install-recommends \
#     build-essential
